### ISSUE TITLE
Errors on spawn.self

### ISSUE THREAD

**Issue by LiEnby** [xerpi/GhidraVitaLoader#3]
from vs0:/app/NPXS10082/spawn.self
F00D refuses to decrypt on retail so you'll need a developer kit or just use sceutils with keys to decrypt

upon running the script you get the error:
```
Error running script: VitaLoader.java
ghidra.program.model.util.CodeUnitInsertionException: Conflicting instruction exists at address 81002600 to 81002603
ghidra.program.model.util.CodeUnitInsertionException: Conflicting instruction exists at address 81002600 to 81002603
	at ghidra.program.database.code.CodeManager.checkValidAddressRange(CodeManager.java:1928)
	at ghidra.program.database.code.CodeManager.createCodeUnit(CodeManager.java:2032)
	at ghidra.program.database.ListingDB.createData(ListingDB.java:422)
	at ghidra.program.flatapi.FlatProgramAPI.createData(FlatProgramAPI.java:1598)
	at ghidra.program.flatapi.FlatProgramAPI.createDWord(FlatProgramAPI.java:1625)
	at ghidra.program.flatapi.FlatProgramAPI.createDwords(FlatProgramAPI.java:1636)
	at VitaLoader.processImports(VitaLoader.java:534)
	at VitaLoader.processModuleInfo(VitaLoader.java:615)
	at VitaLoader.run(VitaLoader.java:665)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:365)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:220)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:198)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:57)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

---------------------------------------------------
Build Date: 2019-Oct-23 1737 EDT
Ghidra Version: 9.1
Java Home: C:\Program Files\Java\jdk-12.0.1
JVM Version: Oracle Corporation 12.0.1
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-MCTFURA
```

**Comment by ghost** [comment]
https://forum.devchroma.nl/index.php/topic,88.msg140.html#msg140

I wrote about this few weeks ago. Just have to clear the conflicting instructions.
